name:                logint-prop-pos-trace
version:             0.1.0.0
github:              "kkeri/logic-interpreters"
license:             BSD3
author:              "Kálmán Kéri"
maintainer:          "kk@metamaya.org"
copyright:           "2021 Kálmán Kéri"

extra-source-files:
- README.md

description:         Logical interpreters for programming

default-extensions:
- ScopedTypeVariables

dependencies:
- base >= 4.7 && < 5

source-dirs: .

executable:
  main:                Main.hs
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
